### ISSUE TITLE
CLI planning

### ISSUE THREAD

**Issue by Peter-ChengTszTung** [oursky/create-react-native-skygear#2]
CLI will run the following steps.

1. run `react-native init {PROJECT_NAME} --template TEMPLATE_PATH`, where TEMPLATE_PATH is our template.
2. Add dev dependencies 
    1. ts related things
    2. linter
    3. prettier
3. Update package.json to add scripts
    1. jest
    2. lint
    3. format
    4. type check
4. Remove a extra line in Podfile which generated by RN-cli
5. Use `implementation` instead of `compile` in build.gradle
6. Drop a unexpected java package generated by RN

Template will includes:
1. redux setup
2. react-navigation
3. i18n
4. Configuration setup

**Comment by cychiuae** [comment]
As discussion, expect an interactive-CLI as ultimate product.

Cli will ask for:

1. Project name
2. skygear endpoint
3. skygear apikey
4. sentry key

and then output a react native project based on the above config options
