### ISSUE TITLE
Road to v2 stable

### ISSUE THREAD

**Issue by cychiuae** [oursky/create-react-native-skygear#40]
### App
- [x] Typescript

~~- [ ] Use Kotlin in Android~~ Since RN assumed Android is in Java, change template default to Kotlin make this generator not work well
- [x] Setup development, nighly, staging and production build settings
- [x] Setup [react native config](https://github.com/luggit/react-native-config)
- [x] Setup Sentry
- [x] Setup [react navigation](https://github.com/react-navigation/react-navigation)
- [x] Setup [i18n](https://github.com/oursky/react-messageformat)
- [x] Setup Redux
- [x] Setup [Skygear](https://github.com/SkygearIO/skygear-SDK-JS)

- [x] Setup travis for checking
- [x] Setup deployment to npm

~~### Server~~
~~- [ ] Generate skygear plugins~~

**Comment by rickmak** [comment]
How about using https://github.com/oursky/react-messageformat in i18n?

**Comment by cychiuae** [comment]
@rickmak i18n is pointed [oursky/react-messageformat](https://github.com/oursky/react-messageformat)

**Comment by cychiuae** [comment]
Done
