### ISSUE TITLE
Project names can only be alphanumeric?

### ISSUE THREAD

**Issue by iam7seven7** [oursky/create-react-native-skygear#46]
When execute command:
`react-native-skygear init testing-app`

Get error:
`testing-app is not a valid name for a project. Please use a valid identifier name (alphanumeric)`

I think it's most reasonable to at least allow '-'

**Comment by cychiuae** [comment]
@iam7seven7 

This issue(#32) opened before. Since we underlying use `react-native-cli` to generate project, that error is actually come from `react-native-cli`. 

You can try `react-native init testing-app`

**Comment by iam7seven7** [comment]
=w= Good to know I'm not the only one
